# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
title: BZR
SEOTitle: BruceZhao's Blog
author: Bruce Zhao
timezone: Asia/Shanghai
paginate: 8 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM                       # use Github Flavored Markdown !important
  
# 国内用多说
# disqus: brucezhaor

#Google Analytics https://developers.google.com/analytics/devguides/collection/analyticsjs/
google_analytics_id: UA-72808482-1
google_analytics_domain: auto

# 自定义永久链接
permalink: /blog/:year/:month/:day/:title/

#默认底图
header-img: /img/default-bg.jpg

RSS: feed.xml
categories_path: categories.html
tags_path: tags.html
archive_path: archive.html
about_path: about.html

BASE_PATH:


# SNS settings

weibo_username:     brucezhaor
facebook_username:     BruceZhaoR
github_username:    BruceZhaoR
google_username:  101167914127123982138/posts
RSS: feed.xml
email: brucezhaor2016@gmail.com
linkedin: bruce-zhao-0ab74287

anchorjs: true                          # 修改在default.html->footer


# 评论系统
# Duoshuo settings
duoshuo_username: brucezhaor
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing
url: "http://brucezhaor.github.io" 

# page Sidebar settings
sidebar-about-description: "致力成为数据攻城狮。"
sidebar-avatar: /img/me1.png     # img前面加`/`绝对引用。



# Friends
friends: [
	{
        title: "Hux-模板来源",
        href: "http://huangxuan.me"
	},{
        title: "谢益辉",
        href: "http://yihui.name"
    },{
        title: "落园",
        href: "http://www.loyhome.cn/"
    },{
        title: "京东-刘思喆",
        href: "http://www.bjt.name/"
    },{
        title: "邱怡轩",
        href: "http://yixuan.cos.name/cn/"
	},{
        title: "JRQ 西南交大",
        href: "http://yixuan.cos.name/cn/"
	}
]



