# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

timezone: Asia/Shanghai
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: brucezhaor
google_analytics: brucezhaor

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Bruce的博客

description: Welcome to my blog
author:
  name: Bruce Zhao
  email: brucezhaor2016@gmail.com
  github: BruceZhaoR
  weibo: brucezhaor
  linkedin: bruce-zhao-0ab74287
  yupoo: brucezhaor/FanAque4/medium.jpg  #主页左侧图片,又拍网链接的照片
  weixin: brucezhaor/Fc4u8KUO/medium.jpg #网页例子  http://pic.yupoo.com/brucezhaor/Fc4u8KUO/medium.jpg
  bio: To be a Data Scientist!

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
archive_path: archive.html

BASE_PATH:
